### ISSUE TITLE
Assign owner to animal

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-52/nashville-kennels-frosty-narwhals#12]
Only employees should be able to add additional owners to animals

**Comment by keosha-w** [comment]
- if current user is an employee - when they click on 
- dropdown with onchange that will call a useEffect POST http method  to assign the selected user as an owner of the animal. 
- ternary statement if owner has been selected add disabled attribute to the dropdown
- then renders the list of owners where the dropdown was...
complexity - 5
